### ISSUE TITLE
Save the Shortened URL.

### ISSUE THREAD

**Issue by modihere** [modihere/url-shortener#7]
Everytime the same url is shortened, different short-url pops up. We will have to resolve this by showing same short-url whenever the same url is asked by the user to be shortened.
The idea in my mind is to store the short-url to database and then fetch it whenever needed.
Implementing it is a tad difficult i think.

Any other suggestions are also welcome.

**Comment by sandeepsajan0** [comment]
I am working on this issue.

**Comment by sandeepsajan0** [comment]
I had almost solve this issue but now it can store only cache data everytime when anyone change the code or refresh the code(save the code) it loses its data because I used a dictionary to store the `url` and `short_id` in _shorturl/views.py_ globally. So everytime when _shorturl/views.py_ refreshes dictionary loses its data.

**Comment by modihere** [comment]
Wait for some time. I need to run a few checks on the app. Will update you before tomorrow morning if you can proceed with your idea.

**Comment by modihere** [comment]
@sandeepsajan0  I am closing this for now. If needed i will reopen it later. And well done.
